// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package owlto_sol_transfer

import ag_binary "github.com/gagliardetto/binary"

type TransferData struct {
	Amount     uint64
	TargetAddr string
}

func (obj TransferData) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `TargetAddr` param:
	err = encoder.Encode(obj.TargetAddr)
	if err != nil {
		return err
	}
	return nil
}

func (obj *TransferData) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `TargetAddr`:
	err = decoder.Decode(&obj.TargetAddr)
	if err != nil {
		return err
	}
	return nil
}
